# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nsa',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
    ]
