# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsa_app', '0002_event_nsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nsa',
            field=models.CharField(max_length=25),
        ),
    ]
