# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsa_app', '0009_auto_20190227_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(upload_to='city_photos/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='event_photos/'),
        ),
    ]
