# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsa_app', '0010_auto_20190227_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile_pics/defaultprofile.png', upload_to='profile_pics/'),
        ),
    ]
