# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsa_app', '0015_city_wide_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='nsa_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_users',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='nsa_app.User'),
            preserve_default=False,
        ),
    ]
